/**
 * Названия субъектов РФ по коду ISO 3166-2 — тем же, что у геометрии карты
 * (geo-data.json) и у бэкенда (shared/geo_regions.py).
 */
export const RU_REGION_NAMES: Record<string, readonly [ru: string, en: string]> = {
  'RU-AD': ['Адыгея', 'Adygea'],
  'RU-AL': ['Республика Алтай', 'Altai Republic'],
  'RU-ALT': ['Алтайский край', 'Altai Krai'],
  'RU-AMU': ['Амурская область', 'Amur Oblast'],
  'RU-ARK': ['Архангельская область', 'Arkhangelsk Oblast'],
  'RU-AST': ['Астраханская область', 'Astrakhan Oblast'],
  'RU-BA': ['Башкортостан', 'Bashkortostan'],
  'RU-BEL': ['Белгородская область', 'Belgorod Oblast'],
  'RU-BRY': ['Брянская область', 'Bryansk Oblast'],
  'RU-BU': ['Бурятия', 'Buryatia'],
  'RU-CE': ['Чечня', 'Chechnya'],
  'RU-CHE': ['Челябинская область', 'Chelyabinsk Oblast'],
  'RU-CHU': ['Чукотский АО', 'Chukotka'],
  'RU-CU': ['Чувашия', 'Chuvashia'],
  'RU-DA': ['Дагестан', 'Dagestan'],
  'RU-IN': ['Ингушетия', 'Ingushetia'],
  'RU-IRK': ['Иркутская область', 'Irkutsk Oblast'],
  'RU-IVA': ['Ивановская область', 'Ivanovo Oblast'],
  'RU-KAM': ['Камчатский край', 'Kamchatka Krai'],
  'RU-KB': ['Кабардино-Балкария', 'Kabardino-Balkaria'],
  'RU-KC': ['Карачаево-Черкесия', 'Karachay-Cherkessia'],
  'RU-KDA': ['Краснодарский край', 'Krasnodar Krai'],
  'RU-KEM': ['Кемеровская область', 'Kemerovo Oblast'],
  'RU-KGD': ['Калининградская область', 'Kaliningrad Oblast'],
  'RU-KGN': ['Курганская область', 'Kurgan Oblast'],
  'RU-KHA': ['Хабаровский край', 'Khabarovsk Krai'],
  'RU-KHM': ['Ханты-Мансийский АО — Югра', 'Khanty-Mansi Okrug'],
  'RU-KIR': ['Кировская область', 'Kirov Oblast'],
  'RU-KK': ['Хакасия', 'Khakassia'],
  'RU-KL': ['Калмыкия', 'Kalmykia'],
  'RU-KLU': ['Калужская область', 'Kaluga Oblast'],
  'RU-KO': ['Коми', 'Komi'],
  'RU-KOS': ['Костромская область', 'Kostroma Oblast'],
  'RU-KR': ['Карелия', 'Karelia'],
  'RU-KRS': ['Курская область', 'Kursk Oblast'],
  'RU-KYA': ['Красноярский край', 'Krasnoyarsk Krai'],
  'RU-LEN': ['Ленинградская область', 'Leningrad Oblast'],
  'RU-LIP': ['Липецкая область', 'Lipetsk Oblast'],
  'RU-MAG': ['Магаданская область', 'Magadan Oblast'],
  'RU-ME': ['Марий Эл', 'Mari El'],
  'RU-MO': ['Мордовия', 'Mordovia'],
  'RU-MOS': ['Московская область', 'Moscow Oblast'],
  'RU-MOW': ['Москва', 'Moscow'],
  'RU-MUR': ['Мурманская область', 'Murmansk Oblast'],
  'RU-NEN': ['Ненецкий АО', 'Nenets Okrug'],
  'RU-NGR': ['Новгородская область', 'Novgorod Oblast'],
  'RU-NIZ': ['Нижегородская область', 'Nizhny Novgorod Oblast'],
  'RU-NVS': ['Новосибирская область', 'Novosibirsk Oblast'],
  'RU-OMS': ['Омская область', 'Omsk Oblast'],
  'RU-ORE': ['Оренбургская область', 'Orenburg Oblast'],
  'RU-ORL': ['Орловская область', 'Oryol Oblast'],
  'RU-PER': ['Пермский край', 'Perm Krai'],
  'RU-PNZ': ['Пензенская область', 'Penza Oblast'],
  'RU-PRI': ['Приморский край', 'Primorsky Krai'],
  'RU-PSK': ['Псковская область', 'Pskov Oblast'],
  'RU-ROS': ['Ростовская область', 'Rostov Oblast'],
  'RU-RYA': ['Рязанская область', 'Ryazan Oblast'],
  'RU-SA': ['Якутия', 'Yakutia'],
  'RU-SAK': ['Сахалинская область', 'Sakhalin Oblast'],
  'RU-SAM': ['Самарская область', 'Samara Oblast'],
  'RU-SAR': ['Саратовская область', 'Saratov Oblast'],
  'RU-SE': ['Северная Осетия', 'North Ossetia'],
  'RU-SMO': ['Смоленская область', 'Smolensk Oblast'],
  'RU-SPE': ['Санкт-Петербург', 'Saint Petersburg'],
  'RU-STA': ['Ставропольский край', 'Stavropol Krai'],
  'RU-SVE': ['Свердловская область', 'Sverdlovsk Oblast'],
  'RU-TA': ['Татарстан', 'Tatarstan'],
  'RU-TAM': ['Тамбовская область', 'Tambov Oblast'],
  'RU-TOM': ['Томская область', 'Tomsk Oblast'],
  'RU-TUL': ['Тульская область', 'Tula Oblast'],
  'RU-TVE': ['Тверская область', 'Tver Oblast'],
  'RU-TY': ['Тыва', 'Tuva'],
  'RU-TYU': ['Тюменская область', 'Tyumen Oblast'],
  'RU-UD': ['Удмуртия', 'Udmurtia'],
  'RU-ULY': ['Ульяновская область', 'Ulyanovsk Oblast'],
  'RU-VGG': ['Волгоградская область', 'Volgograd Oblast'],
  'RU-VLA': ['Владимирская область', 'Vladimir Oblast'],
  'RU-VLG': ['Вологодская область', 'Vologda Oblast'],
  'RU-VOR': ['Воронежская область', 'Voronezh Oblast'],
  'RU-YAN': ['Ямало-Ненецкий АО', 'Yamalo-Nenets Okrug'],
  'RU-YAR': ['Ярославская область', 'Yaroslavl Oblast'],
  'RU-YEV': ['Еврейская АО', 'Jewish Autonomous Oblast'],
  'RU-ZAB': ['Забайкальский край', 'Zabaykalsky Krai'],
}
